app/products/forms.py
# app/admin/forms.py

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, BooleanField 
from wtforms.validators import DataRequired
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from ..models import Product,Catalog
from flask_wtf.file import FileField, FileRequired, FileAllowed
from flask_wtf import Form
from flask_uploads import UploadSet, IMAGES
images = UploadSet('images', IMAGES)
class ProductForm(FlaskForm):
    """
    Form for admin to add or edit a department
    """
    common_name = StringField('Name', validators=[DataRequired()])
    price = StringField('Price', validators=[DataRequired()])
    upload = FileField('Image', validators=[FileRequired(),FileAllowed(images, 'Images only!')])
    imgurl = StringField('ImgURL')
    color = StringField('Color')
    size = StringField('Size')
    catalog_id = QuerySelectField(query_factory=lambda: Catalog.query.all(),get_label="catalog_name")
    available = BooleanField('Available', default=True)
    submit = SubmitField('Submit')

app/products/__init__.py
# app/product/__init__.py  (Blueprint creation)

from flask import Blueprint

product = Blueprint('product', __name__)

# can use from main import views
from . import views, errors

app/products/views.py
# app/main/views.py

from flask import render_template, session, redirect, url_for, current_app, jsonify, request, flash, app
from datetime import datetime
from .. import db
from ..email import send_email
# from forms import ProductForm
from app.products import product
from ..models import Product, Order, Order_detail, Catalog, User
from flask_login import login_user, logout_user, login_required, current_user
#import paypalrestsdk
import stripe, os
from flask import current_app

stripe_keys = {
  'secret_key': 'sk_test_uxtuIOeAfAyn2AYpImH7Mjft',
  'publishable_key': 'pk_test_sRa1igLaBVBHhNtVkUPAyBAi'
}
stripe.api_key = stripe_keys['secret_key']
# Normally, if you refer to an undefined variable in a Jinja template,
# Jinja silently ignores this. This makes debugging difficult, so we'll
# set an attribute of the Jinja environment that says to make this an
# error.

# app.jinja_env.undefined = jinja2.StrictUndefined


@product.route('/stripecharge', methods=['POST'])
@login_required
def stripecharge():
    # Amount in cents
    amount = 0
    for order in session['cart']:
        amount = amount + order[1] * float(order[2])
    customer = stripe.Customer.create(
        email = current_app.config['MAIL_USERNAME'],
        source=request.form['stripeToken']
    )
    # print customer.id
    charge = stripe.Charge.create(
        customer=customer.id,
        amount=int(amount * 100),
        currency='usd',
        description='ByTaiwan Patment'
    )
    # print charge
    if charge['paid'] == True :
        current_order = Order(user_id=current_user.id, payment_id=charge['customer'] + '-' + charge['id'], email=charge['source']['name'] , status=True)
        db.session.add(current_order)
        # db.session.flush()
        db.session.commit()
        total = 0
        
        for order in session['cart']:
            order_detail = Order_detail(user_id=current_user.id, product_id=order[4], product_name=order[0], quantity=order[1], price=order[2], order_id=int(current_order.id))
            db.session.add(order_detail)
            total = total + int(order[1]) * float(order[2])
            
        db.session.commit()
        order = Order.query.filter_by(id=current_order.id).first()
        order.total = total
        db.session.commit()
        user = User.query.filter_by(id=order.user_id).first()
        send_email(user.email, 'Confirm Your Order', 'product/email/order', user=user, order=order)
        
        
        flash('Order ID:%s Created! Shipout ASAP.' % (charge['customer'] + '-' + charge['id']))
        message = True
    orders = Order.query.filter_by(user_id=current_user.id, payment_id=charge['customer'] + '-' + charge['id']).paginate(1,1,error_out=False)
    catalogs = Catalog.get_all()
    return render_template("product/order.html", orders=orders, catalogs=catalogs, message=message)


@product.route("/catalogs/<int:id>/<int:page>")
# @login_required
def list_products(id=1,page=1):
    """Return page showing all the products has to offer"""
    per_page=4
    catalogs = Catalog.get_all()
    if id :
        products = Product.query.filter_by(catalog_id=id).paginate(page,per_page,error_out=False)
    else:
        products = Product.get_all().paginate(page,per_page,error_out=False)
    return render_template("product/all_products.html",
                           product_list=products, catalogs=catalogs, catalog_id=id)


@product.route("/<int:id>")
# @login_required
def show_product(id):
    """Return page showing the details of a given product.

    Show all info about a product. Also, provide a button to buy that product.
    """
    catalogs = Catalog.get_all()
    product = Product.get_by_id(id)
    return render_template("product/product_details.html",
                           display_product=product, catalogs=catalogs, catalog_id=id)


@product.route("/cart")
@login_required
def shopping_cart():
    """Display content of shopping cart."""
    if "cart" in session.keys():
        pass
    else:
        session["cart"] = []
    # TODO: Display the contents of the shopping cart.
    #   - The cart is a list in session containing products added
    total = 0
    for order in session['cart']:
        total = total + order[1] * float(order[2])
    catalogs = Catalog.get_all()
    return render_template("product/cart.html",
                            cart=session['cart'],user=current_user, catalogs=catalogs, total=total, publishkey=stripe_keys['publishable_key'])


@product.route("/remove_from_cart/<string:name>")
@login_required
def remove_from_cart(name):
    index = 0
    for order in session['cart']:
        if order[0] == name:
            target_index = index
        index = index + 1  
    
    session['cart'].pop(target_index)
    flash("Product removed from cart successfully!")
    catalogs = Catalog.get_all()
    total = 0
    for order in session['cart']:
        total = total + order[1] * float(order[2])
    return render_template("product/cart.html",
                            cart=session['cart'],user=current_user, catalogs=catalogs, total=total, publishkey=stripe_keys['publishable_key'])


@product.route("/add_to_cart/<int:id>")
@login_required
def add_to_cart(id):
    """Add a product to cart and redirect to shopping cart page.

    When a product is added to the cart, redirect browser to the shopping cart
    page and display a confirmation message: 'Successfully added to cart'.
    """
    if "cart" in session.keys():
        pass
    else:
        session["cart"] = []
    product = Product.get_by_id(id)
    qty = int(request.args.get('qty'))
    total = float(product.price) * qty
    common_name = product.common_name
    price = product.price_str()
    if len(session['cart']) > 0:
        new_item = True
        for old_order in session['cart']:
            # print "the for loop ran"
            if old_order[0] == common_name:
                # print "the if ran"
                old_order[1] += qty
                old_order[3] += total
                new_item = False
        if new_item:
            # print "the else in the for loop ran"
            order = [common_name, qty, price, total, id]
            session['cart'].append(order)
        
    else:
        # print "the else outside ran"
        order = [common_name, qty, price, total, id]
        session['cart'].append(order)

    # TODO: Finish shopping cart functionality
    #   - use session variables to hold cart list
    total = 0
    for order in session['cart']:
        total = total + order[1] * float(order[2])
    flash("Product added to cart successfully!")
    catalogs = Catalog.get_all()
    return render_template("product/cart.html",
                            cart=session['cart'],user=current_user, catalogs=catalogs, total=total, publishkey=stripe_keys['publishable_key'])
    # return render_template("cart.html", product_name=test_product, product_qty=test_qty, product_price=test_price, product_total=total)


@product.route("/clean")
@login_required
def clean():
    """Checkout customer, process payment, and ship products."""
    # from session

    flash("Success. cart already cleaned!!!!")
    catalogs = Catalog.get_all()
    session['cart'] = []
    return redirect("/product/cart")


@product.route("/order/<int:page>")
@login_required
def shopping_order(page=1):
    """Display content of shopping order."""
    per_page = 5
    # TODO: Display the contents of the shopping cart.
    #   - The cart is a list in session containing products added
    orders = Order.query.filter_by(user_id=current_user.id).paginate(page,per_page,error_out=False)
    catalogs = Catalog.get_all()
    return render_template("product/order.html",
                            orders=orders, catalogs=catalogs)


@product.route("/order_detail/<int:id>")
@login_required
def shopping_order_detail(id):
    catalogs = Catalog.get_all()
    order_details = Order_detail.query.filter_by(order_id=id)
    return render_template("product/order_detail.html",
                            order_details=order_details, catalogs=catalogs)

app/templates/product/all_products.html
<!-- app/templates/product/all_products.html -->

{% extends "base.html" %}

{% block title %}ByTaiwan - All Product{% endblock %}

{% block page_content %}
<div class="page-header">
	{% if catalog_id %}
    <h2>{{catalogs[catalog_id - 1]}}</h2>
    {% else %}
    <h2>All Catalog</h2>
	{% endif %}
</div>
    <div id="product-list" class="row">
      {% for product in product_list.items %}
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 product-summary">

              <div class="well">
                  <h3><a href="{{ url_for('product.show_product', id=product.id ) }}"</a>{{ product.common_name }}</h3>
                  <a href="{{ url_for('product.show_product', id=product.id ) }}">
                      <img src ="{{ url_for('static', filename='product/images/'+  product.imgurl) }}" class="img-circle img-responsive center-block"">
                  </a>

                  <div class="price">Price : €{{ product.price_str() }}</div>
                  <a class="btn btn-primary" href="{{ url_for('product.show_product', id=product.id ) }}">Details</a>
              </div>

          </div>
      {% endfor %}
    </div>
    <div class="text-center">
		{% if product_list.has_prev %}<a href="{{ url_for('product.list_products',id = catalog_id, page=product_list.prev_num) }}">&lt;&lt; Newer posts</a>{% else %}&lt;&lt; Pre Pages{% endif %} | 
		{% if product_list.has_next %}<a href="{{ url_for('product.list_products',id = catalog_id, page=product_list.next_num) }}">Older posts &gt;&gt;</a>{% else %}Next Pages &gt;&gt;{% endif %}
	</div>
{% endblock %}

app/templates/product/cart.html
<!-- app/templates/product/cart.html -->
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}

{% block title %}ByTaiwan - Cart{% endblock %}

{% block page_content %}

    <div class="page-header">
    	<a href="{{ url_for("product.clean")}}" class="btn btn-large btn-primary">Clean Cart</a>
	</div>
<table class="table table-striped">
    <thead>
        <tr>
            <th></th>
            <th>Product Name</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        {%if cart %}
        {% for order in cart %}
        <tr>
        	<td><a href="{{url_for("product.remove_from_cart",name = order[0]) }}" class="glyphicon glyphicon-trash"></a></td>
            
            <td>{{ order[0] }}</td>
            <td>€{{ order[2] }}</td>
            <td>{{ order[1] }}</td>
            <td>€{{ order[3] }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td>No items in cart.</td>
        </tr>
        {% endif %}
    </tbody>
</table>
<div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-center-block">
            <div class="well text-center">
			  <form action="/product/stripecharge" method="post">
			  <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
			    <article>
			      <label>
			        <span>Amount is €{{total}}</span>
			      </label>
			    </article>
			    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
			            data-key={{ publishkey }}
			            data-description="ByTaiwan Payment"
			            data-amount={{total * 100}}
			            data-locale="auto"
			            data-zip-code="true"
			            data-currency="EUR"
			            data-billing-address = "true"
			            data-email = {{user.email}}>
			    </script>
			  </form>
			</div>
		</div>
</div>
{% endblock %}

app/templates/product/order.html
<!-- app/templates/product/order.html -->
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}

{% if message %}
{{ utils.flash.message() }}
{% endif %}

{% block title %}ByTaiwan - Order{% endblock %}

{% block page_content %}

    <div class="page-header">
    <a href="{{ url_for('product.shopping_cart') }}" class="btn btn-large btn-primary">Cart</a>
	</div>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Order_ID</th>
            <th>PaymentID-PayerID</th>
            <th>email</th>
            <th>Order_Time</th>
            <th>Total</th>
            <th>Shipout</th>
        </tr>
    </thead>
    <tbody>
        {%if orders.items %}
        {% for order in orders.items %}
        <tr>
            <td><a href="{{ url_for("product.shopping_order_detail",id =order.id) }}">{{ order.id }}</a></td>
            <td>{{ order.payment_id }}</td>
            <td>{{ order.email }}</td>
            <td>{{ (order.order_datetime).strftime("%Y-%m-%d %H:%M:%S") }}</td>
            <td>€{{ order.total }}</td>
            {% if order.shipout  %}
            <td>Shipout</td>
            {% else %}
            <td>Didn't shipout</td>
            {% endif %}
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td>No orders.</td>
        </tr>
        {% endif %}
    </tbody>
</table>
    <div class="text-center">
		{% if orders.has_prev %}<a href="{{ url_for('product.shopping_order', page=orders.prev_num) }}">&lt;&lt; Newer posts</a>{% else %}&lt;&lt; Pre Pages{% endif %} | 
		{% if orders.has_next %}<a href="{{ url_for('product.shopping_order', page=orders.next_num) }}">Older posts &gt;&gt;</a>{% else %}Next Pages &gt;&gt;{% endif %}
	</div>
{% endblock %}

app/templates/product/order_detail.html
<!-- app/templates/product/order.html -->
{% extends "base.html" %}

{% block title %}ByTaiwan - Order{% endblock %}

{% block page_content %}
        <form>
  		<input type="button" value="&laquo; Previous" onclick="history.back()">
		</form>   
<table class="table table-striped">
    <thead>
        <tr>
            <th>Product_ID</th>
            <th>Product_Name</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        {%if order_details %}
        {% for order_detail in order_details %}
        <tr>
            <td>{{ order_detail.product_id }}</td>
            <td>{{ order_detail.product_name }}</td>
            <td>€{{ order_detail.price }}</td>
            <td>{{ order_detail.quantity }}</td>
            <td>€{{ order_detail.price | float * order_detail.quantity | int }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td>No orders.</td>
        </tr>
        {% endif %}
    </tbody>
</table>
{% endblock %}

app/templates/product/product.html
<!-- app/templates/product/product.html -->

{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}TeaAsia - AddProduct{% endblock %}

{% block page_content %}
<div class="page-header">
{% if add_product %}
    <h1>Add Product</h1>
{% else %}
	<h1>Edit Product</h1>
{% endif %}
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/product/product_details.html
{% extends 'base.html' %}
{% block title %}ByTaiwan - Product Detial{% endblock %}

{% block page_content %}
    <h2>Product : {{ display_product.common_name }}</h2>
    <div class="row">
    	<p></p>
		<p></p>	        		
	    <div style='border-bottom:1px solid #ccc;'></div>
    	<p></p>
		<p></p>	   	    
	    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">

	        <img src="{{ url_for('static', filename='product/images/'+ display_product.imgurl) }}" class="img-thumbnail center-block" alt="Responsive image" style="width:100%" >

	    </div>
    	<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
          <ul>
            <p><h2><li>Product type: {{ display_product.product_type }}</li></h2></p>
            <p><h2><li>Color: {{ display_product.color }}</li></h2></p>
            <p><h2><li>Size: {{ display_product.size }}</li></h2></p>
            {% if display_product.available %}
              <p><h2><li>Status : In stock</li></h2></p>
            {% else %}
              <p><li class='warning'>Warning! This product was no in stock.</li></p>
            {% endif %}
          </ul>

	        <h3>Price per package : €{{ display_product.price_str() }}</h3>
	    	<div class="well text-center">
		        <form action="/product/add_to_cart/{{ display_product.id }}">
		            <label>
		                <input type="number" name="qty" value="1" min="1" max="10">
		            </label>
		            <label>
		                <input type="submit" class="btn btn-large btn-primary" value="Add to Cart">
		            </label>
		        </form>
	        </div>
	        </div>
        </div>
        <p>
        <p>
{% endblock %}

app/templates/product/products.html
<!-- app/templates/product/products.html -->
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}

{% block title %}TeaAsia - Product{% endblock %}

{% block page_content %}
<div class="content-section">
  <div class="outer">
    <div class="middle">
      <div class="inner">
        <br/>
        {{ utils.flashed_messages() }}
        <br/>
        <h1 style="text-align:center;">Products</h1>
        {% if products %}
          <hr class="intro-divider">
          <div class="center">
            <table class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th width="5%"> ID </th>
                  <th width="20%"> Name </th>
                  <th width="20%"> ImgURL </th>
                  <th width="10%"> Price </th>
                  <th width="10%"> Color </th>
                  <th width="10%"> Size </th>
                  <th width="5%"> Available </th>
                  <th width="10%"> Catalog </th>
                  <th width="5%"> Edit </th>
                  <th width="5%"> Delete </th>
                </tr>
              </thead>
              <tbody>
              {% for product in products %}
                <tr>
                  <td> {{ product.id }} </td>
                  <td> {{ product.common_name }} </td>
                  <td> {{ product.imgurl }} </td>
                  <td> ${{ product.price }} </td>
                  <td> {{ product.color }} </td>
                  <td> {{ product.size }} </td>
                  <td> {{ product.available }} </td>
                  <td> {{ product.product_type}}</td>
                  <td>
                    <a href="{{ url_for('product.edit_product', id=product.id) }}">
                      <i class="fa fa-pencil"></i> Edit 
                    </a>
                  </td>
                  <td>
                    <a href="{{ url_for('product.delete_product', id=product.id) }}">
                      <i class="fa fa-trash"></i> Delete 
                    </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
          <div style="text-align: center">
        {% else %}
          <div style="text-align: center">
            <h3> No product have been added. </h3>
            <hr class="intro-divider">
        {% endif %}
          <a href="{{ url_for('product.add_product') }}" class="btn btn-default btn-lg">
            <i class="fa fa-plus"></i>
            Add Product
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}