app/taiwan/__init__.py
# app/auth/__init__.py

from flask import Blueprint

taiwan = Blueprint('taiwan', __name__)

from . import views

app/taiwan/views.py
# app/main/views.py

from flask import render_template, session, redirect, url_for, current_app, jsonify, request, flash, app
from datetime import datetime
from .. import db
# from forms import ProductForm
from app.taiwan import taiwan
from ..models import Story, Catalog
from flask_login import login_user, logout_user, login_required, current_user
#import paypalrestsdk

# Normally, if you refer to an undefined variable in a Jinja template,
# Jinja silently ignores this. This makes debugging difficult, so we'll
# set an attribute of the Jinja environment that says to make this an
# error.

# app.jinja_env.undefined = jinja2.StrictUndefined


@taiwan.route("/stories/<int:page>")
# @login_required
def list_stories(page=1):
    """Return page showing all the products has to offer"""
    per_page=4
    catalogs = Catalog.get_all()
    stories = Story.query.order_by(Story.post_datetime.desc()).filter_by(available = True).paginate(page,per_page,error_out=False)
    return render_template("taiwan/all_stories.html",
                           story_list=stories, catalogs=catalogs)


@taiwan.route("/show_story/<int:id>")
#@login_required
def show_story(id):
    """Return page showing the details of a given product.

    Show all info about a product. Also, provide a button to buy that product.
    """
    catalogs = Catalog.get_all()
    story = Story.get_by_id(id)
    return render_template("taiwan/story_details.html",
                           display_story=story, catalogs=catalogs)

@taiwan.route("/hit_story/<int:id>")
#@login_required
def hit_story(id):
    """Return page showing the details of a given product.

    Show all info about a product. Also, provide a button to buy that product.
    """
    catalogs = Catalog.get_all()
    story = Story.get_by_id(id)
    hitnumber = story.hitnumber + 1
    story.hitnumber = hitnumber
    db.session.commit
    return jsonify({'value' : str(hitnumber)})

app/templates/taiwan/all_stories.html
<!-- app/templates/product/all_products.html -->

{% extends "base.html" %}

{% block title %}ByTaiwan - All Story{% endblock %}

{% block page_content %}
<div class="page-header">
    <h2 class="shadow">Hello, {% if current_user.is_authenticated %}{{ current_user.username }}{% else %}Stranger{% endif %}!</h2>
</div>


    <div id="story-list" class="row">
      {% for story in story_list.items %}
          <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 product-summary">
              <div class="well">
                  <h3><a href="{{ url_for('taiwan.show_story', id=story.id ) }}">{{ story.title }}</a></h3>                  
                  <a href="{{ url_for('taiwan.show_story', id=story.id ) }}">
                      <img src ="{{ url_for('static', filename='story/images/'+ story.imgurl) }}" class="img-responsive center-block" style="width:100%">
                  </a>
                  </br>
                  <p><div class="location">Location : {{ story.location }}</div></p>
				  <p><div class="author">Author : {{ story.author }}</div></p>
                  <p><div class="post_datetime">PostDate : {{ story.post_datetime.strftime('%Y-%m-%d') }}</div></p>
              </div>
          </div>
      {% endfor %}
    </div>
    <div class="text-center">
		{% if story_list.has_prev %}<a href="{{ url_for('taiwan.list_stories', page=story_list.prev_num) }}">&lt;&lt; Newer posts</a>{% else %}&lt;&lt; Pre Pages{% endif %} | 
		{% if story_list.has_next %}<a href="{{ url_for('taiwan.list_stories', page=story_list.next_num) }}">Older posts &gt;&gt;</a>{% else %}Next Pages &gt;&gt;{% endif %}
	</div>
{% endblock %}

app/templates/taiwan/story_details.html
{% extends 'base.html' %}
{% block title %}ByTaiwan - Story Detial{% endblock %}

{% block head %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script type=text/javascript> var $SCRIPT_ROOT = {{ request.script_root|tojson|safe }}; </script> 
{{ super() }}
<script type=text/javascript>
  $(function() {
    $("#hitBtn").click(function() {
         $.ajax({
            type: "GET",
            url: $SCRIPT_ROOT + "/taiwan/hit_story/{{display_story.id}}",
            contentType: "application/json; charset=utf-8",
            success: function(data) {
                $('#hitResult').text( data.value);
            }
        });     
    });
  });
</script>
{% endblock %}

{% block page_content %}
    <h2>Title : {{ display_story.title }}</h2>
	<div class="center-block">    
	    <div class="row">
	        	    <p></p>
					<p></p>	        		
	        <div style='border-bottom:1px solid #ccc;'></div>
	        	    <p></p>
					<p></p>
	        <div class="col-sm-12 col-md-12 col-lg-12">

	            <img src="{{ url_for('static', filename='story/images/'+ display_story.imgurl) }}" class="img-responsive center-block" style="width:100%">
	        	    <p></p>
					<p></p>
					
	        </div>
		</div>
		<div class="row">
	        <div class="col-sm-12 col-md-12 col-lg-12">
					<SPAN STYLE="float:right">
					    <p>
				        <button type="button" id='hitBtn' name='hitBtn' class="btn btn-default btn-sm">
				          <span class="glyphicon glyphicon-thumbs-up"></span> Like
				        </button>
					    </p>
					</SPAN>
					<SPAN STYLE="float:left">
						<span class="glyphicon">&#xe125; :&nbsp</span><div id="hitResult" style="display: inline">{{display_story.hitnumber|string}}</div>
					</SPAN> 
					<DIV STYLE="clear:both"></DIV>
     	            <p><h3>Location : {{ display_story.location }}</h3></p>
			        <div class="description">
		       				<p><h3>  {{ display_story.description }}</h3></p>
		       		</div>
		       		</br>
		       		<div class="text-right">
		       		<p><h3>Author : {{ display_story.author }} / {{ display_story.post_datetime.strftime('%Y-%m-%d %H:%M:%S') }}</h3></p>
		        	</div>
		        </div>
	        </div>
	    </div>
    	<p></p>
		<p></p>
{% endblock %}